Huffman Algorithm: HuffmanStructures.h File Reference
HuffmanStructures.h File Reference
Las esctructuras y funciones usadas en el Algoritmo de Huffman.
Data Structures
struct bits
Almacena el byte correspondiente, su tamaño y sus bits de la codificacion de Huffman.
struct data
Almacena un byte y las veces que aparecio en el archivo.
struct node
Estructura del arbol de Huffman.
struct Heap
Almacena un arreglo de nodos.
Macros
#define PESOBIT(bpos) 1 << bpos
#define CONSULTARBIT(var, bpos) (*(unsigned *)&var & PESOBIT(bpos)) ? 1 : 0
Typedefs
typedef struct Heap Heap
Functions
int isEmpty (struct node *root)
int isLeaf (struct node *root)
void pushTree (struct node *root, unsigned char byte, int frecuency)
struct node * mergeNodes (struct node *node1, struct node *node2)
void getBits (struct node *HuffmanTree, struct bits bytesCode[], int bits, int bitsSize)
int getCharacters (struct node *HuffmanTree, unsigned char *cadena, int *posInString, int posInBits, unsigned char *byteToWrite)
Heap * CreateHeap (int capacity)
void insert (Heap *heap, struct node *node)
void heapify_bottom_top (Heap *heap, int index)
void heapify_top_bottom (Heap *heap, int parent_node)
struct node * PopMin (Heap *heap)
void insertTree (struct data bytesFrecuency[], struct node roots[], Heap *heap)
struct node * mergeTrees (Heap *heap)
Detailed Description
Las esctructuras y funciones usadas en el Algoritmo de Huffman.
Author
Victor Torres
Leilani Sotelo
Guillermo Sanchez
Version
1.0
Definition in file HuffmanStructures.h.
Function Documentation
CreateHeap()
Heap* CreateHeap (int capacity)
Crea una estructura Heap en memoria dinamica dada su capacidad, la cual es un arreglo de nodos.
Parameters
capacity es la capacidad que queremos que tenga heap
Returns
el apuntador a la estructura heap creada
 {
     Heap *heap = (Heap *)malloc(sizeof(Heap));
     heap->count = 0;
     heap->capacity = capacity;
     heap->arrayOfNodes = (struct node **)malloc(capacity * sizeof(struct node));
     return heap;
 }
References Heap::capacity, and Heap::count.
getBits()
void getBits (struct node * HuffmanTree, struct bits bytesCode[], int bits, int bitsSize)
Obtiene la codificaciond de Huffman correspondiente a los bytes. La guarda en un arreglo de struct junto con el tamaño de bits correspondiente. La codificacion se obtiene recorriendo el arbol inorder y cada vez registramos un 0 o un 1 si nos vamos a la izquierda o derecha, al final si es nodo hoja, guardamos lo que llevamos
Parameters
HuffmanTree el arbol de Huffman
bytesCode el arreglo donde se guarda el byte, su codificacion y tamaño
bits los bits con los que inicia el nodo que por defecto es 0
bitsSize el tamaño de los bits que por defecto es 0
 {
     if (!isEmpty(HuffmanTree))
     {                                                                     //if notempty
         getBits(HuffmanTree->left, bytesCode, (bits << 1), sizeBits + 1); // irte al nodo izq, sumandole un 0
         if (isLeaf(HuffmanTree))
         {
             int hashKey = HuffmanTree->data.byte;
             bytesCode[hashKey].bits = bits;
             bytesCode[hashKey].byte = HuffmanTree->data.byte;
             bytesCode[hashKey].sizeBits = sizeBits;
         }
         getBits(HuffmanTree->right, bytesCode, (bits << 1) + 1, sizeBits + 1); //irte al nodo der sumandole un 1
     }
 }
References bits::bits, bits::byte, data::byte, node::data, isEmpty(), isLeaf(), node::left, node::right, and bits::sizeBits.
getCharacters()
int getCharacters (struct node * HuffmanTree, unsigned char * cadena, int * posInString, int posInBits, unsigned char * byteToWrite)
Obtiene el byte correspondiente a la codificacion de Huffman. Recorre el arbol analizando si es 0 o 1 el bit en el que esta para irse a la izquierda o a la derecha, cuando detecta que ya ha llegado a un nodo hoja, regresa en byteToWrite el valor del byte dado la cadena de bits
Parameters
HuffmanTree el arbol de Huffman
cadena la cadena de bytes leidos del archivo comprimido
posInString la posicion del arreglo de la cadena
posInBits la posicion de bits en la que vamos en relacion a un byte
byteToWrite la variable donde guardaremos el byte correspondiente
Returns
la posicion en bits en donde nos quedamos en relacion a un byte
 {
     if (isLeaf(HuffmanTree))
     {
         *byteToWrite = HuffmanTree->data.byte;
         return posInBits;
     }
     else
     {
         if (posInBits < 0)
         {
             (*posInString)++;
             posInBits = 7;
         }
         if (((int)CONSULTARBIT(cadena[(*posInString)], (posInBits))) == 0)
             return getCharacters(HuffmanTree->left, cadena, posInString, (posInBits)-1, byteToWrite);
         else
             return getCharacters(HuffmanTree->right, cadena, posInString, posInBits - 1, byteToWrite);
     }
 }
References data::byte, node::data, and isLeaf().
Referenced by writeFile().
heapify_bottom_top()
void heapify_bottom_top (Heap * heap, int index)
Ordena los elementos del arreglo de nodos, haciendo que el elemento mas pequeño sea la rama principal de nuestro arbol.
Parameters
Heap es el monticulo al que vamos a ordenar su arreglo de nodos
index es el indice en este caso el numero de elementos que hay que ordenar
 {
     struct node *temp;
     int parent_node = (index - 1) / 2;
     if (heap->arrayOfNodes[parent_node]->data.frequency > heap->arrayOfNodes[index]->data.frequency)
     {
         temp = heap->arrayOfNodes[parent_node];
         heap->arrayOfNodes[parent_node] = heap->arrayOfNodes[index];
         heap->arrayOfNodes[index] = temp;
         heapify_bottom_top(heap, parent_node);
     }
 }
References node::data.
Referenced by insert().
heapify_top_bottom()
void heapify_top_bottom (Heap * heap, int parent_node)
Ordena los elementos del arreglo de nodos, haciendo que el elemento mas pequeño sea la rama principal de nuestro arbol,este lo usamos al momento de retirar el elemento principal de nuestro Heap, debido a que el ordenamiento lo realiza a partir de nuestra raiz hacia los elementos hijos del arbol.
Parameters
Heap es el monticulo al que vamos a ordenar su arreglo de nodos
parent_node es el indice del elemento padre de nuestro nodo para realizar
 {
     int left = parent_node * 2 + 1;
     int right = parent_node * 2 + 2;
     int min;
     struct node *temp;
     if (left >= heap->count || left < 0)
         left = -1;
     if (right >= heap->count || right < 0)
         right = -1;
     if (left != -1 && heap->arrayOfNodes[left]->data.frequency < heap->arrayOfNodes[parent_node]->data.frequency)
         min = left;
     else
         min = parent_node;
     if (right != -1 && heap->arrayOfNodes[right]->data.frequency < heap->arrayOfNodes[min]->data.frequency)
         min = right;
     if (min != parent_node)
     {
         temp = heap->arrayOfNodes[min];
         heap->arrayOfNodes[min] = heap->arrayOfNodes[parent_node];
         heap->arrayOfNodes[parent_node] = temp;
         heapify_top_bottom(heap, min);
     }
 }
References Heap::count, node::data, node::left, and node::right.
Referenced by PopMin().
insert()
void insert (Heap * heap, struct node * node)
Inserta Nodos en la estructura de datos, indicando el Heap donde se desea hacer la incersion, seguido del nodo que se desea insertar, simempre y cuando la capacidad de Heap no haya sido exedida.
Parameters
heap es el monticulo donde vamos a insertar el nodo
node es el nodo a insertar dentro del monticulo
 {
     if (heap->count < heap->capacity)
     {
         heap->arrayOfNodes[heap->count] = node;
         heapify_bottom_top(heap, heap->count);
         heap->count++;
     }
 }
References Heap::capacity, Heap::count, and heapify_bottom_top().
Referenced by insertTree(), and mergeTrees().
insertTree()
void insertTree (struct data bytesFrecuency[], struct node roots[], Heap * heap)
Inserta en la cola de prioridad los nodos. EL numero de nodos que inserta son los bytes distintos que aparecieron en el archivo
Parameters
bytesFrecuency el arreglo de struct donde viene el byte y su frecuencia
roots el arreglo de nodos que trae todos los bytes y su frecuencia
heap la cola de prioridad
 {
     int i;
     for (i = 0; i < 256; i++)
     {
         if (bytesFrecuency[i].frequency > 0)
         {
             pushTree(&roots[i], bytesFrecuency[i].byte, bytesFrecuency[i].frequency);
             insert(heap, &roots[i]);
         }
     }
 }
References insert(), and pushTree().
isEmpty()
int isEmpty (struct node * root)
Nos dice si nodo en el arbol de Huffman es vacio o no.
Parameters
root el nodo a comparar
Returns
1 si el arbol es vacio
0 si el arbol no es vacio
 { return root == NULL; }
Referenced by getBits().
isLeaf()
int isLeaf (struct node * root)
Nos dice si nodo en el que estamos es un nodo hoja.
Parameters
root el nodo a analizar
Returns
1 si el nodo es hoja
0 si el nodo no es hoja
 { return root->left == NULL && root->right == NULL; }
References node::left, and node::right.
Referenced by getBits(), and getCharacters().
mergeNodes()
struct node* mergeNodes (struct node * node1, struct node * node2)
Une dos nodos en un nodo ancestro comun
Parameters
node1 el primer nodo a unir que estara del lado izquierdo
node2 el segundo nodo a unir que estara del lado derecho
Returns
el nodo comun que tiene como hijos a ambos nodos
 {
     struct node *new_node = malloc(sizeof(struct node));
     new_node->data.byte = 0;
     new_node->left = node1;
     new_node->right = node2;
     new_node->data.frequency = node1->data.frequency + node2->data.frequency;
     return new_node;
 }
References data::byte, node::data, node::left, and node::right.
Referenced by mergeTrees().
mergeTrees()
struct node* mergeTrees (Heap * heap)
Une todos los nodos hoja en un solo, llamado Arbol de Huffman. Usando la cola de prioridad saca los dos nodos de menor frecuencia suma sus dos frecuencia y los une en un nodo padre, haciendo esto hasta que solo quede un nodo padre el cual contiene a todos los nodos de los bytes leidos
Parameters
heap la cola de prioridad con los nodos de los bytes leidos
Returns
el Arbol de Huffman
 {
     while (heap->count > 1)
     {
         struct node *node1 = PopMin(heap);
         struct node *node2 = PopMin(heap);
         insert(heap, mergeNodes(node1, node2));
     }
     return PopMin(heap);
 }
References Heap::count, insert(), mergeNodes(), and PopMin().
PopMin()
struct node* PopMin (Heap * heap)
Elmina el elemento mas pequeño de una cola de prioridad
Parameters
Heap Es la estructura heap
Returns
nodo eliminado
 {
     struct node *pop;
     if (heap->count == 0)
     {
         printf("Heap is Empty.\n");
         return NULL;
     }
     pop = heap->arrayOfNodes[0];
     heap->arrayOfNodes[0] = heap->arrayOfNodes[heap->count - 1];
     heap->count--;
     heapify_top_bottom(heap, 0);
     return pop;
 }
References Heap::count, and heapify_top_bottom().
Referenced by mergeTrees().
pushTree()
void pushTree (struct node * root, unsigned char byte, int frecuency)
Inserta dado un byte y una frecuencia, las inserta en el nodo del arbol
Parameters
root el arbol de Huffman donde se insertara
byte el byte correspondiente de su frecuencia
frecuency la frecuencia correspondiente del byte
 {
     root->data.frequency = frecuency;
     root->data.byte = byte;
     root->left = NULL;
     root->right = NULL;
 }
References data::byte, node::data, node::left, and node::right.
Referenced by insertTree().